/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.student.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Student service. Represents a row in the &quot;student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.student.services.model.impl.StudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.student.services.model.impl.StudentImpl}.
 * </p>
 *
 * @author Aditya
 * @see Student
 * @see com.student.services.model.impl.StudentImpl
 * @see com.student.services.model.impl.StudentModelImpl
 * @generated
 */
public interface StudentModel extends BaseModel<Student> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the student ID of this student.
	 *
	 * @return the student ID of this student
	 */
	public int getStudentId();

	/**
	 * Sets the student ID of this student.
	 *
	 * @param studentId the student ID of this student
	 */
	public void setStudentId(int studentId);

	/**
	 * Returns the name of this student.
	 *
	 * @return the name of this student
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this student.
	 *
	 * @param name the name of this student
	 */
	public void setName(String name);

	/**
	 * Returns the lastname of this student.
	 *
	 * @return the lastname of this student
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this student.
	 *
	 * @param lastname the lastname of this student
	 */
	public void setLastname(String lastname);

	/**
	 * Returns the std of this student.
	 *
	 * @return the std of this student
	 */
	@AutoEscape
	public String getStd();

	/**
	 * Sets the std of this student.
	 *
	 * @param std the std of this student
	 */
	public void setStd(String std);

	/**
	 * Returns the address of this student.
	 *
	 * @return the address of this student
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this student.
	 *
	 * @param address the address of this student
	 */
	public void setAddress(String address);

	/**
	 * Returns the phone of this student.
	 *
	 * @return the phone of this student
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this student.
	 *
	 * @param phone the phone of this student
	 */
	public void setPhone(String phone);

	/**
	 * Returns the gender of this student.
	 *
	 * @return the gender of this student
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this student.
	 *
	 * @param gender the gender of this student
	 */
	public void setGender(String gender);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Student student);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Student> toCacheModel();

	@Override
	public Student toEscapedModel();

	@Override
	public Student toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}